# Generated by Django 3.1.7 on 2021-03-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210304_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='click_num',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='fav_num',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_desc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='goods_front_iamge',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='ship_free',
        ),
    ]
